### ISSUE TITLE
CFD Scores aren't in "Download Designs" spreadsheet

### ISSUE THREAD

**Issue by marcus-r-kelly** [pinellolab/PrimeDesign#2]
I have been using the hosted PrimeDesign at https://drugthatgene.pinellolab.partners.org/. I have checked the option to calcuate CFD score, and these scores do display correctly in my browser for the sgRNAs. However, when I download designs using the "Download Designs" button, there is a column for CFD score in the spreadsheet for which no values are given. I suspect this is a bug.

**Comment by jyhsu15** [comment]
Thank you for catching this, should be fixed now!

**Comment by marcus-r-kelly** [comment]
Thanks! Also, I notice that the CFD scores for all nicking guides in PE3b solutions have 0 CFD. I will admit that my understanding of CFD is not that deep, but is this correct?

**Comment by jyhsu15** [comment]
Seems like calculating CFD is case-sensitive. Should be a super quick fix! Thank you.

**Comment by marcus-r-kelly** [comment]
Looks good now, thank you!
